// 2020 F=ma A problems
{
  contest: 'F=ma', year: 2020, number: 1,
  topic: 'energy',
  problem: 'F=ma 2020 A Problem #1. A ball is launched straight toward the ground from height h. When it bounces off the ground, it loses half of its kinetic energy. It reaches a maximum height of 2h before falling back to the ground again. What was the initial speed of the ball?',
  choices: ['sqrt(gh)', 'sqrt(2gh)', 'sqrt(3gh)', 'sqrt(4gh)', 'sqrt(6gh)'],
  correct_answer: 'E',
  solution: 'Using energy conservation: E0 = mgh + (1/2)mv0^2. After bounce, half the KE is lost, so remaining energy equals mg(2h). Thus mgh + (1/2)mv0^2 = 2*mg(2h), giving v0 = sqrt(6gh).',
},
{
  contest: 'F=ma', year: 2020, number: 2,
  topic: 'rotational',
  problem: 'F=ma 2020 A Problem #2. A rigid ball of radius R is rolling without slipping along the rib of a right-angle chute. [Diagram: side view shows ball rolling along a V-shaped chute; cross-section shows ball resting in right-angle groove with contact points A and B on the sides, center O, lowest point P, and highest point Q marked.] Which of the point(s) of the ball have the maximum speed?',
  choices: ['All points have the same speed.', 'The contact points A and B.', 'The center O.', 'The lowest point P.', 'The highest point Q.'],
  correct_answer: 'E',
  solution: 'Points A and B are stationary since the ball rolls without slipping on the rib. Since the contact points are below center, the velocity v + omega x r is maximized at the highest point Q, which is farthest from the instantaneous axis of rotation through A and B.',
},
{
  contest: 'F=ma', year: 2020, number: 3,
  topic: 'energy',
  problem: 'F=ma 2020 A Problem #3. When an axe is swung with kinetic energy E directly at a piece of wood, the edge of the axe is buried a depth L into the wood. If the axe is swung with kinetic energy 2E, how deep will it be buried into the wood? Assume that the axe is wedge-shaped with a constant angle and that the force per unit contact area between the axe and the wood during the impact is proportional to the depth.',
  choices: ['2^(1/4) L', '2^(1/3) L', 'sqrt(2) L', '2L', '4L'],
  correct_answer: 'B',
  solution: 'The energy required to enter the wood scales as L^3: the force per unit contact area scales as L (spring-like), and the contact length scales as L (wedge shape), so force ~ L^2, and integrating force over depth gives E ~ L^3. Doubling energy gives depth 2^(1/3) L.',
},
{
  contest: 'F=ma', year: 2020, number: 4,
  topic: 'rotational',
  problem: 'F=ma 2020 A Problem #4. Four identical rods, each of mass m and length 2d, are joined together to form a square. The square is then spun around its center at an angular frequency of omega. What is the magnitude of the force that the joints between the rods (at the corners of the square) must bear?',
  choices: ['m*omega^2*d/2', 'm*omega^2*d/sqrt(2)', 'm*omega^2*d', 'sqrt(2)*m*omega^2*d', '2*m*omega^2*d'],
  correct_answer: 'B',
  solution: 'Consider one rod: every point on it is at horizontal distance d from the center, so the centripetal force on the rod is m*omega^2*d directed radially outward. By symmetry, the joint forces act perpendicular to the diagonals. Balancing forces: 2*F_joint*cos(pi/4) = m*omega^2*d, giving F_joint = m*omega^2*d/sqrt(2).',
},
{
  contest: 'F=ma', year: 2020, number: 5,
  topic: 'oscillations',
  problem: 'F=ma 2020 A Problem #5. A pendulum of length L oscillates inside a box. A person picks up the box and gently shakes it horizontally with frequency omega and a fixed amplitude for a fixed time. The final amplitude can be maximized if omega satisfies',
  choices: ['omega = sqrt(g/L)', 'omega = 2*sqrt(g/L)', 'omega = (1/2)*sqrt(g/L)', 'There will be no effect on the amplitude for any value of omega.', 'None of the above'],
  correct_answer: 'A',
  solution: 'In the frame of the box, the horizontal shaking acts as a driving force on the pendulum. To maximize the amplitude, the driving frequency should match the natural frequency (resonance), so omega = sqrt(g/L).',
},
{
  contest: 'F=ma', year: 2020, number: 6,
  topic: 'gravity',
  problem: 'F=ma 2020 A Problem #6. A planet is orbiting a star in a circular orbit of radius r0. Over a very long period of time, much greater than the period of the orbit, the star slowly and steadily loses 1% of its mass. Throughout the process, the planet\'s orbit remains approximately circular. The final orbit radius is closest to',
  choices: ['1.02*r0', '1.01*r0', 'r0', '0.99*r0', '0.98*r0'],
  correct_answer: 'B',
  solution: 'Angular momentum L = mvr is conserved. For a circular orbit, mv^2 = GMm/r, so M is proportional to v^2*r = L^2/(m^2*r). Thus M*r = const, and a 1% decrease in M gives a 1% increase in r.',
},
{
  contest: 'F=ma', year: 2020, number: 7,
  topic: 'gravity',
  problem: 'F=ma 2020 A Problem #7. An astronaut standing on the exterior of the international space station wants to dispose of three pieces of trash. They face the station\'s direction of travel with the Earth to their left. From the astronaut\'s perspective, the three pieces are thrown (I) left, (II) right, and (III) up. To the astronaut\'s frustration, some of the pieces of trash return to the space station after several hours. They are',
  choices: ['II only', 'III only', 'I and II', 'II and III', 'I, II, and III'],
  correct_answer: 'E',
  solution: 'By Kepler\'s third law, T^2 is proportional to a^3 where a is the semimajor axis. The astronaut\'s throw has negligible impact on total energy, hence negligible impact on a and the orbital period T. After one full orbit, all three pieces return to the space station.',
},
{
  contest: 'F=ma', year: 2020, number: 8,
  topic: 'kinematics',
  problem: 'F=ma 2020 A Problem #8. [Diagram: A velocity versus position plot shows v as a linear function of x, starting from v=0 at x=0 and increasing linearly.] Which of the following choices is the correct acceleration vs. position plot of the particle?',
  choices: ['[Plot: a is constant (horizontal line) for all x]', '[Plot: a is zero at x=0 and curves upward (concave up)]', '[Plot: a is zero at x=0 and increases linearly with x]', '[Plot: a is nonzero constant then drops]', '[Plot: a is zero at x=0 and curves downward]'],
  correct_answer: 'C',
  solution: 'Since v = kx for some constant k, differentiating with respect to time gives a = k*(dx/dt) = k*v = k^2*x. Thus acceleration is linear in x, starting from zero at x=0 and increasing linearly.',
},
{
  contest: 'F=ma', year: 2020, number: 9,
  topic: 'mechanics',
  problem: 'F=ma 2020 A Problem #9. A block of mass m is attached to a massless string. The string is passed over a massless pulley and the end of the string is fixed in place. The horizontal part of the string has length L. Now a small mass m is hung from the horizontal part of the string, and the system comes to equilibrium. [Diagram: A pulley system where a block hangs on one side, and a mass is hung from the horizontal section of the string.] Neglecting friction everywhere, the tension at the end of the string is',
  choices: ['mg/2', 'mg', '3mg/2', '2mg', '3mg'],
  correct_answer: 'B',
  solution: 'In equilibrium, the tensions on both sides of any massless pulley must be equal for torque balance. The same logic applies to the hung mass (it acts like another pulley). Hence the tension everywhere in the string is mg.',
},
{
  contest: 'F=ma', year: 2020, number: 10,
  topic: 'mechanics',
  problem: 'F=ma 2020 A Problem #10. (Continuation of Problem 9) During this process, the block has been raised by approximately a height',
  choices: ['0.15L', '0.23L', '0.31L', '0.37L', '0.40L'],
  correct_answer: 'A',
  solution: 'For force balance on the hung mass, the two string segments must each make a 30 degree angle with the horizontal, and the mass hangs at the midpoint. The horizontal section of length L becomes two tilted sections each of length L/sqrt(3). The total string length increases by L(2/sqrt(3) - 1) ≈ 0.155L, which equals the height the block is raised.',
},
{
  contest: 'F=ma', year: 2020, number: 11,
  topic: 'mechanics',
  problem: 'F=ma 2020 A Problem #11. The maximal tension per area a material can sustain without failure is called its tensile strength. Plain steel has a tensile strength of 415 MPa. What is the maximal mass one can hang on a vertical steel rod of negligible mass and a diameter of 2 cm?',
  choices: ['1300 kg', '5200 kg', '13000 kg', '52000 kg', 'The answer depends on the length of the steel rod.'],
  correct_answer: 'C',
  solution: 'Balancing forces: m_max * g = sigma * pi * r^2. With sigma = 415e6 Pa, r = 0.01 m, and g = 10 m/s^2: m_max = 415e6 * pi * (0.01)^2 / 10 ≈ 13000 kg.',
},
{
  contest: 'F=ma', year: 2020, number: 12,
  topic: 'oscillations',
  problem: 'F=ma 2020 A Problem #12. A point mass m is glued inside a massless hollow rod of length L at an unknown location. When the rod is pivoted at one end, the period of small oscillations is T. When the rod is pivoted at the other end, the period of small oscillations is 2T. How far is the mass from the center?',
  choices: ['L/8', 'L/6', 'L/4', '3L/10', '2L/5'],
  correct_answer: 'D',
  solution: 'For a point mass on a pivot, T is proportional to sqrt(distance from pivot). If T and 2T are the periods, the ratio of distances is 4:1. So the mass is at distance L/5 from one end and 4L/5 from the other, placing it 3L/10 from the center.',
},
{
  contest: 'F=ma', year: 2020, number: 13,
  topic: 'rotational',
  problem: 'F=ma 2020 A Problem #13. A ballerina with moment of inertia I is quickly twirling with angular velocity omega. In her hand she has a pen of mass m at a radius R from her axis of rotation. The ballerina releases the pen. Afterward, what happens to the vertical component of the angular momentum of the system consisting of the ballerina and the pen? You may ignore all friction, but not gravity or normal forces.',
  choices: ['It decreases until the pen hits the floor.', 'It increases until the pen hits the floor.', 'It always stays the same.', 'It initially stays the same, but decreases when the pen hits the floor.', 'It initially stays the same, but increases when the pen hits the floor.'],
  correct_answer: 'C',
  solution: 'There are no external vertical torques in this problem. Both gravity and normal forces are vertical, so they produce no vertical torque. Therefore the vertical component of angular momentum of the system is conserved at all times.',
},
{
  contest: 'F=ma', year: 2020, number: 14,
  topic: 'mechanics',
  problem: 'F=ma 2020 A Problem #14. Two blocks of mass m are placed on top of each other, and the bottom block is placed on a frictionless ground. The static and kinetic coefficients of friction between the two blocks are mu_s and mu_k. The blocks are at rest initially. When a constant horizontal force F is applied to the bottom block, which of the following graphs could show its acceleration as a function of F? [Diagram: Five plots of acceleration a vs. force F are shown with various shapes.] Note: The problem statement contained a typo (mu_s < mu_k), so credit was given for all answers.',
  choices: ['[Plot: linear increase]', '[Plot: linear increase, then jump up, then steeper linear increase]', '[Plot: linear increase then curve]', '[Plot: linear then plateau then linear]', '[Plot: two linear segments with different slopes, no jump]'],
  correct_answer: 'B',
  solution: 'For small F, blocks move together with a = F/(2m), linear in F. At the threshold where friction can\'t keep the top block moving with the bottom, the blocks slip. Since mu_k < mu_s (intended), friction drops suddenly, causing a jump in acceleration. Above threshold, a = (F - mu_k*mg)/m, linear with steeper slope. Note: credit was given for all answers due to a typo in the problem.',
},
{
  contest: 'F=ma', year: 2020, number: 15,
  topic: 'fluids',
  problem: 'F=ma 2020 A Problem #15. As shown in the figure, a vessel contains two types of liquid: the liquid with density rho_1 on top and rho_2 on the bottom. The depth of the top liquid is h1, and the interface area between the top and the bottom liquid is s1. The bottom liquid has a depth of h2. The area of the bottom of the vessel is s2. [Diagram: A tapered vessel wider at top than bottom, with two liquid layers.] What is the gauge pressure at the bottom of the vessel?',
  choices: ['(rho_1*h1 + rho_2*h2)*g', '(rho_1*s1*h1 + rho_2*s2*h2)*g/s2', '(1/2)*(rho_1 + rho_2)*(h1 + h2)*g', '(rho_1 + rho_2)*(h1 + h2)*g', 'rho_2*(h1 + h2)*g'],
  correct_answer: 'A',
  solution: 'Gauge pressure depends only on depth, not on container shape. At the liquid interface, gauge pressure is rho_1*h1*g. From there to the bottom, pressure increases by rho_2*h2*g. Total gauge pressure at the bottom is (rho_1*h1 + rho_2*h2)*g.',
},
{
  contest: 'F=ma', year: 2020, number: 16,
  topic: 'energy',
  problem: 'F=ma 2020 A Problem #16. Liquid droplets store a given amount of potential energy per unit surface area, due to their surface tension. When two identical, nearly spherical liquid droplets coalesce on a certain type of surface, part of this energy can be converted into upward kinetic energy, causing the coalesced droplet to jump. Assuming the conversion is 100% efficient, how does the maximum height h depend on the radius r of the initial droplets?',
  choices: ['h is proportional to r', 'h is proportional to r^(1/2)', 'h is proportional to r^(-1/2)', 'h is proportional to r^(-1)', 'h is proportional to r^(-2)'],
  correct_answer: 'D',
  solution: 'The change in surface area (and hence energy released) scales as r^2. The mass scales as r^3. Since energy = mgh, we have r^2 ~ r^3 * h, giving h proportional to r^(-1).',
},
{
  contest: 'F=ma', year: 2020, number: 17,
  topic: 'momentum',
  problem: 'F=ma 2020 A Problem #17. Paul the Giant stands outside on a force-meter calibrated in Newtons, which reads 5000 N. Paul is wearing a large cowboy hat, which has horizontal cross-sectional area A = 1 m^2 and completely covers both him and the scale when seen from directly above. At time t = 0, rain begins to fall vertically downward on Paul, and any rain that hits his hat is collected in the hat\'s brim. The raindrops have a constant downward speed of 1 m/s, and the rain accumulates on the ground at a rate of 1 mm/s. What is the reading (in N) on the scale as a function of the time t > 0 (in s)? The density of water is 1000 kg/m^3.',
  choices: ['5001 + 11t', '5001 + 10t', '5000 + 11t', '5001 + 1.1t', '5001 + t'],
  correct_answer: 'B',
  solution: 'Three contributions: (1) Paul\'s weight = 5000 N (constant). (2) Weight of collected water: volume rate = 1 mm/s * 1 m^2, so mass rate = 1 kg/s, giving weight = 10t N. (3) Momentum transfer from stopping rain: dp/dt = (mass rate)*v = 1 kg/s * 1 m/s = 1 N (constant). Total = 5000 + 1 + 10t = 5001 + 10t.',
},
{
  contest: 'F=ma', year: 2020, number: 18,
  topic: 'rotational',
  problem: 'F=ma 2020 A Problem #18. A massless rigid rod is pivoted at one end, and a mass M is at the other end. Originally, the rod rotates frictionlessly about the pivot with a uniform angular velocity such that the mass M has speed v. The rotating rod collides with another mass M at its midpoint, which then sticks to the rod. After the collision, what is the kinetic energy of the system?',
  choices: ['(1/4)*M*v^2', '(1/3)*M*v^2', '(7/18)*M*v^2', '(2/5)*M*v^2', '(1/2)*M*v^2'],
  correct_answer: 'D',
  solution: 'Angular momentum about the pivot is conserved. Let v\' be the final speed of the end mass; the midpoint mass has speed v\'/2. Conservation: M*v*r = M*v\'*r + M*(v\'/2)*(r/2), giving v\' = 4v/5. Final KE = (1/2)*M*(4v/5)^2 + (1/2)*M*(2v/5)^2 = (2/5)*M*v^2.',
},
{
  contest: 'F=ma', year: 2020, number: 19,
  topic: 'rotational',
  problem: 'F=ma 2020 A Problem #19. A system of cylinders and plates is set up as shown. The cylinders all have radius r, and roll without slipping to the right with angular velocity omega. [Diagram: Three layers of cylinders separated by plates, with a floor at bottom and a top plate. Each layer has cylinders rolling between two plates.] What is the speed of the top plate?',
  choices: ['omega*r', '2*omega*r', '3*omega*r', '4*omega*r', '6*omega*r'],
  correct_answer: 'E',
  solution: 'Each cylinder rotates about its contact point with the surface below it. The top of each cylinder moves at 2*omega*r relative to the surface below. The first plate moves at 2*omega*r. The second layer of cylinders adds another 2*omega*r, and the third layer adds another 2*omega*r. Total speed of top plate = 6*omega*r.',
},
{
  contest: 'F=ma', year: 2020, number: 20,
  topic: 'mechanics',
  problem: 'F=ma 2020 A Problem #20. A car is driving against the wind at a constant speed v0 relative to the ground. The wind direction is always opposite to the car\'s velocity, but its speed fluctuates about an average speed of v relative to the ground. The air drag force is A*v_rel^2, where A is a constant and v_rel is the relative speed between the car and the wind. What is the average rate P of energy dissipation due to the air resistance?',
  choices: ['P = A*v0*(v0 + v)^2', 'P > A*v0*(v0 + v)^2', 'P < A*v0*(v0 + v)^2', 'Both (B) and (C) are possible depending on how v fluctuates.', 'Both (A) and (C) are possible depending on how v fluctuates.'],
  correct_answer: 'B',
  solution: 'Let u = v0 + v. The relative speed is u + delta_u where delta_u averages to zero. Instantaneous power = A*v0*(u + delta_u)^2 = A*v0*(u^2 + 2u*delta_u + (delta_u)^2). On average, the 2u*delta_u term vanishes but (delta_u)^2 > 0, so P > A*v0*(v0 + v)^2.',
},
{
  contest: 'F=ma', year: 2020, number: 21,
  topic: 'mechanics',
  problem: 'F=ma 2020 A Problem #21. A circular table has radius R and N > 2 equally spaced legs of length h attached to its perimeter. Suppose the table has a uniform mass density with total mass m, and neglect the mass of the legs. Assuming the table does not slip, the minimum horizontal force needed to tip over the table is',
  choices: ['mgR/h', '(mgR/h)*sin((N-2)*pi/(2N))', '(mgR/h)*cos(pi/N)', '(mgR/h)*tan((N-2)*pi/(2N))', '(mgR/h)*sin(pi/(2N))'],
  correct_answer: 'C',
  solution: 'The optimal push is directed toward the midpoint of two adjacent legs. The table tips about the line connecting those two legs. The perpendicular distance from the center to this line is R*cos(pi/N). Balancing torques: F*h = mg*R*cos(pi/N), so F = mgR*cos(pi/N)/h. Note: choices B and C are equivalent, and credit was given for both.',
},
{
  contest: 'F=ma', year: 2020, number: 22,
  topic: 'momentum',
  problem: 'F=ma 2020 A Problem #22. A collision occurs between two masses. In each inertial reference frame, one can compute the change in total momentum Delta_P and the change in total kinetic energy Delta_K due to the collision. Which of the following is true?',
  choices: ['Delta_P and Delta_K do not depend on the frame.', 'Delta_P and Delta_K do not depend on the frame for perfectly elastic collisions, but Delta_P may depend on the frame for inelastic collisions.', 'Delta_P and Delta_K do not depend on the frame for perfectly elastic collisions, but Delta_K may depend on the frame for inelastic collisions.', 'Delta_P and Delta_K do not depend on the frame for perfectly elastic collisions, but both may depend on the frame for inelastic collisions.', 'Delta_P and Delta_K may both depend on the frame, for both perfectly elastic and inelastic collisions.'],
  correct_answer: 'A',
  solution: 'Momentum is always conserved in collisions, so Delta_P = 0 in every frame. For elastic collisions, Delta_K = 0 in every frame. For inelastic collisions, the kinetic energy lost goes to thermal energy, which is frame-invariant (it depends on relative velocities). So Delta_K is also frame-independent. Both quantities are frame-independent for all collision types.',
},
{
  contest: 'F=ma', year: 2020, number: 23,
  topic: 'measurement',
  problem: 'F=ma 2020 A Problem #23. Steve determines the spring constant k of a spring by applying a force F to it and measuring the change in length Delta_x. The tools he uses to measure F and Delta_x both have a constant absolute uncertainty, leading to an uncertainty in k of delta_k_S. If Tiffany measures the same spring constant with the same tools but by using a force that is five times larger, what will her uncertainty in k be in terms of delta_k_S?',
  choices: ['delta_k_T = 0.04*delta_k_S', 'delta_k_T = 0.08*delta_k_S', 'delta_k_T = 0.2*delta_k_S', 'delta_k_T = 0.4*delta_k_S', 'delta_k_T = 0.5*delta_k_S'],
  correct_answer: 'C',
  solution: 'The relative uncertainty in k satisfies (delta_k/k)^2 = (delta_F/F)^2 + (delta_x/Delta_x)^2. Quintupling the force quintuples both F and Delta_x, reducing relative uncertainties by a factor of 5. Since k stays the same, delta_k is reduced by a factor of 5, so delta_k_T = 0.2*delta_k_S.',
},
{
  contest: 'F=ma', year: 2020, number: 24,
  topic: 'mechanics',
  problem: 'F=ma 2020 A Problem #24. A mass m is connected to one end of a zero-length spring with spring constant k. The other end of the spring is connected to a frictionless bearing mounted around a horizontal pole so that the mass can swing in a vertical circle of radius R around the pole. [Diagram: A horizontal pole with a spring connecting to a mass that traces a vertical circle of radius R, with vertical distance h between the center of the circle and the pole.] What is the vertical distance h between the center of the circular orbit and the axis of the pole? Assume that both the diameter of the pole and the rest length of the spring are negligible compared to R.',
  choices: ['sqrt(mgR/k)', 'R*sqrt((R + mg/k)/(R - mg/k))', 'R - mg/k', 'mg/k', 'sqrt(R^2 - (mg/k)^2)'],
  correct_answer: 'D',
  solution: 'Consider the instant when the mass moves vertically upward (acceleration is purely horizontal). The vertical spring force must balance gravity. The spring length is sqrt(h^2 + R^2) and makes angle theta with horizontal where sin(theta) = h/sqrt(h^2 + R^2). Vertical force = k*sqrt(h^2 + R^2)*sin(theta) = k*h = mg, giving h = mg/k.',
},
{
  contest: 'F=ma', year: 2020, number: 25,
  topic: 'oscillations',
  problem: 'F=ma 2020 A Problem #25. A ball of negligible radius and mass m is connected to two ideal springs. Each spring has rest length l0. The springs are connected to the ball inside a box of height 2*l0, and the ball is allowed to come to equilibrium. [Diagram: A vertical box of height 2*l0 with spring k1 attached from top and spring k2 attached from bottom to a ball at equilibrium.] Under what condition is this equilibrium point stable with respect to small horizontal displacements?',
  choices: ['k1 > k2', 'k2 > k1', 'k1 - k2 > mg/l0', 'k1*k2/(k1 + k2) > mg/l0', 'k1*k2/(k1 - k2) > mg/l0'],
  correct_answer: 'C',
  solution: 'At equilibrium, the ball is displaced below center by z0 = -mg/(k1 + k2). For a small horizontal displacement x, the top spring provides a restoring force while the bottom spring provides a destabilizing force. The net horizontal force is restoring when k1/(l0 - z0) > k2/(l0 + z0). Substituting z0 and simplifying gives the stability condition k1 - k2 > mg/l0.',
},
